#ifndef PRINTDELIVERYINTERFACE_IDL
#define PRINTDELIVERYINTERFACE_IDL
#include "BasicDataType.idl"

module PrintDelivery{

  typedef sequence<double> DoubleSeq;
   
  struct RETURN_ID {
    long id;
    string comment;
  };

  struct PrintData{
	  string sendPCode;
	  string sendAddress;
	  string PCode;
	  string address;
      string sendName;
	  string Name;
	  string objectName;
	  DoubleSeq option;
  };
    
  const long OK = 0;
  const long NG = -1;
  const long STATUS_ERR = -2;
  const long VALUE_ERR = -3;
  const long NOT_SV_ON_ERR = -4;
  const long FULL_MOTION_QUEUE_ERR = -5;
  const long NOT_IMPLEMENTED = -6;
  
  interface PrintDeriveryInterface {
	  RETURN_ID PrintDeliveryData(in PrintData data);
    
  };
};
#endif //PRINTDELIVERYINTERFACE_IDL
